# Spring properties
spring:
  application:
     name: account-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

# HTTP Server
server:
  port: 10001   # HTTP (Tomcat) port