# Spring properties
spring:
  application:
    name: configuration-service
  profiles:
    active: native
#  cloud:
#    config:
#      server:
#        native:
#          #searchLocations: file:./config/{application},file:./config/{application}/{profile} # Trial 01
#         searchLocations: file://./config/,file:./config/{application},file:./config/{application}/{profile}

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

# HTTP Server
server:
  port: 10003
