#!/bin/bash

docker-compose -f services/docker-compose.yml up -d
echo "Waiting for discovery and configuration service to start ..."
sleep 60s
docker-compose -f apps/docker-compose.yml -f apps/docker-compose-override-local.yml up